server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_food?characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 12345

      web-stat-filter:
        enabled: true
        url-pattern: /*
  redis:
    host: localhost
    port: 6379
    password:


mybatis:
  configuration:
    map-underscore-to-camel-case: true